import { expect, test } from 'bun:test';

test('US-009 armed DOM placement uses the shared exact-identity limit boundary', async () => {
	const source = await Bun.file(new URL('./OrderBook.svelte', import.meta.url)).text();
	expect(source).toContain("async function clickLadderPrice(side: 'buy' | 'sell', price: number, stop = false)");
	expect(source).toContain('if (!$clickPlacementMode)');
	expect(source).toContain('marketKey: $selectedMarket.marketKey');
	expect(source).toContain("type: stop ? 'stop' : 'limit'");
	expect(source).toContain('wouldCrossSpread(side, price, $orderBook.bids[0]?.price, $orderBook.asks[0]?.price)');
	expect(source).toContain('await fetchOpenOrders();');
	expect(source).toContain("handleLadderRowClick('buy', bid.price, event)");
	expect(source).toContain("handleLadderRowClick('sell', ask.price, event)");
	expect(source).toContain('event.shiftKey');
	expect(source).toContain("type: stop ? 'stop' : 'limit'");
	expect(source).toContain('triggerPrice: stop ? price : undefined');
	expect(source).toContain('Post-only cannot be used with a DOM stop order');
	expect(source).toContain('function ordersAtPrice(price: number)');
	expect(source).toContain('function positionsAtPrice(price: number)');
	expect(source).toContain('position.entryPrice.toFixed(decimals) === normalizedPrice');
	expect(source).toContain('data-testid={`dom-position-${position.id}`}');
	expect(source).toContain('async function cancelLadderOrder(orderId: string, marketIdentity?: string)');
	expect(source).toContain('cancelOrder(orderId, marketIdentity)');
	expect(source).toContain("$: canCancelKnownOrders = marketProfile.executable && $isConnected && $executionStatus === 'live' && $accountSyncStatus === 'live' && $marketDataStatus === 'live';");
	expect(source).toContain('return canCancelKnownOrders');
	expect(source).toContain('if (!canCancelKnownOrders)');
	expect(source).toContain("async function cancelLadderSide(side: 'buy' | 'sell')");
	expect(source).toContain('order.side === side && marketMatches($selectedMarket, order.apiCoin, order.marketKey)');
	expect(source).toContain('if (await cancelLadderOrder(order.id, order.apiCoin ?? order.marketKey)) cancelled += 1');
	expect(source).toContain("Cancel was accepted but authoritative order reconciliation is unavailable");
	expect(source).toContain("cancelLadderSide('buy')");
	expect(source).toContain("cancelLadderSide('sell')");
	expect(source).toContain('data-testid="dom-quick-size"');
	expect(source).toContain('bind:value={$orderSize}');
	expect(source).toContain('setOrderSizePercent(percent)');
	expect(source).toContain('async function flattenDomMarket()');
	expect(source).toContain("buildPositionCloseIntent(position, $marketRegistry, $selectedMarket, $orderBook, 'market')");
	expect(source).toContain('placeOrder(close.intent)');
	expect(source).toContain('([ordersRefreshed, positionsRefreshed]) => ordersRefreshed && positionsRefreshed');
	expect(source).toContain('Flatten was accepted but authoritative reconciliation is unavailable');
	expect(source).toContain('async function reverseDomMarket()');
	expect(source).toContain('buildPositionReversePlan(position, $marketRegistry, $selectedMarket, $orderBook)');
	expect(source).toContain('reverseCloseReconciliation(get(positions), planned.plan)');
	expect(source).toContain('Reverse paused: close leg is not yet flat in the authoritative account snapshot');
	expect(source).toContain('Reverse left the position flat: opposite-side open leg was rejected');
	expect(source).toContain('Confirm reverse');
	expect(source).toContain('Cancel ${order.side} order at ${ask.price}');
	expect(source).toContain('Cancel ${order.side} order at ${bid.price}');
	expect(source).toContain('async function modifyLadderOrder(orderId: string, newPrice: number)');
	expect(source).toContain('modifyOrderPrice(orderId, marketIdentity, newPrice)');
	expect(source).toContain('function finishLadderOrderDrag(price: number)');
	expect(source).toContain('onmouseup={() => finishLadderOrderDrag(ask.price)}');
	expect(source).toContain('onmouseup={() => finishLadderOrderDrag(bid.price)}');
	expect(source).toContain('function scheduleLadderRecenter(): void');
	expect(source).toContain("ladderCenter.scrollIntoView({ block: 'center' })");
	expect(source).toContain('function onLadderScroll(): void');
	expect(source).toContain('data-testid="dom-ladder-viewport"');
	expect(source).toContain('aria-label="Recenter DOM ladder"');
	expect(source).toContain('data-testid="dom-follow-status"');
	expect(source).toContain('{#each visibleAsks as ask (ask.price)}');
	expect(source).toContain('{#each visibleBids as bid (bid.price)}');
});
