[package]
name = "vice-dex-hyperliquid"
version.workspace = true
edition.workspace = true

[dependencies]
vice-core = { path = "../core" }
vice-dex-trait = { path = "../dex-trait" }
async-trait = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
