/* AUTO-GENERATED manifest of v2 lesson files per course (filenames as on disk).
   Loaded eagerly by index.html; the engine reads window.LT_V2_FILES in
   ensureV2LessonsLoaded(n) to lazy-load a course's lessons on demand.
   Regenerate if lesson files are added/renamed. */
window.LT_V2_FILES = {
  "1": [
    "01_Introduction.js",
    "02_Understanding_Price_Action.js",
    "03_Components_of_a_Market.js",
    "04_Support_and_Resistance.js",
    "05_Trending_Markets.js",
    "06_Rangebound_Markets.js",
    "07_What_is_Market_Structure.js",
    "08_Identifying_Market_Structure.js",
    "09_Timeframes.js",
    "10_HTF_Scenario.js",
    "11_LTF_Scenario.js",
    "12_Risk_Management.js",
    "13_Achieving_Profitability.js",
    "14_Optimizing_Returns.js",
    "15_Outro.js"
  ],
  "2": [
    "01_Trading_Styles.js",
    "02_Introduction.js",
    "03_Types_of_Trades.js",
    "04_Entering_Trades.js",
    "05_Exiting_Trades.js",
    "06_Price_Action_Formations.js",
    "07_Price_Action_Examples.js",
    "08_Volume_Analysis.js",
    "09_Volume_Examples.js",
    "10_Classical_Chart_Patterns.js",
    "11_Classical_Pattern_Examples.js",
    "12_Fibonacci.js",
    "13_Ichimoku_Kinko_Hyo.js",
    "14_Ichimoku_Market_Scenario.js",
    "15_Oscillators.js",
    "16_Financial_Instruments.js",
    "17_Outro.js",
    "18_Divergences.js"
  ],
  "3": [
    "01_Introduction.js",
    "02_Order_Types.js",
    "03_Deposit_and_Withdraw.js",
    "04_Understanding_the_Orderbook.js",
    "05_Getting_into_Positions.js",
    "06_Executing_Orders.js",
    "07_Understanding_Contracts.js",
    "08_Understanding_Leverage.js",
    "09_Applying_Leverage.js",
    "10_Margin_Management.js",
    "11_Identifying_Access_Points.js",
    "12_Trading_SR.js",
    "13_Trading_Ranges.js",
    "14_Range_Market_Scenario.js",
    "15_Crafting_Your_System.js",
    "16_Applying_Your_System.js",
    "17_Recording_Your_System.js",
    "18_Developing_a_Traders_Mindset.js",
    "19_The_Art_of_Meditation.js",
    "20_The_Reality_Behind_Trading_Fulltime.js",
    "21_Outro.js"
  ],
  "4": [
    "01_Introduction.js",
    "02_Liquidity_Theory.js",
    "03_Identifying_Liquidity.js",
    "04_Liquidity_Structures.js",
    "05_Liquidity_Scenarios.js",
    "06_Who_is_in_Control_Primer.js",
    "07_Sentiment_Analysis_Variables.js",
    "08_Funding_Rate.js",
    "09_Open_Interest.js",
    "10_Cumulative_Delta.js",
    "11_Future_Basis.js",
    "12_Applying_Sentiment.js",
    "13_Trend_Buddy.js",
    "14_PAL.js",
    "15_Heuristics.js",
    "16_FSVZO.js",
    "17_Crayons.js",
    "18_Genie.js",
    "19_Platform_Overview.js",
    "20_Liquidation_Levels.js",
    "21_Liquidation_Level_Scenario.js",
    "22_Positions_Heatmap.js",
    "23_Combining_Sentiment_Data.js",
    "24_Trading_Activity.js",
    "25_Hyblock_Indicators.js",
    "26_Kijun_Sen.js",
    "27_C_Clamps_and_Kumo_Pockets.js",
    "28_Edge_to_Edge.js",
    "29_Ichimoku_Market_Scenario.js",
    "30_Outro.js"
  ]
};
