#!/usr/bin/env node
/* gen-academy.js — builds /academy: the Liquidity Theory app AS a Vice Hub
   place. ONE chrome: no second masthead — the hub's nav pills are woven into
   the app's own top header, so the page reads as a single product (owner
   rejected both the iframe and the stacked double-header). Runs at Vercel
   build (chained after gen-seo) so the shell can never drift from the app:
     · root-relative assets absolutized (the page serves at /academy)
     · hub nav pills injected INTO .top-header, before the BTC ticker
     · title/canonical/noindex swapped — this door never competes in search
   Runtime lazy loads (lessons-v2, audio) resolve relative to /academy/ and
   fall back to root via the vercel.json rewrite /academy/:path* → /:path*.
   The generator FAILS LOUDLY if its anchors vanish — that is the drift alarm,
   not a bug. */
'use strict';

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SRC = path.join(ROOT, 'index.html');
const OUT_DIR = path.join(ROOT, 'academy');
const OUT = path.join(OUT_DIR, 'index.html');

const HUB = 'https://vicesuite.com/hub';

/* pill styles ride in <head>; everything namespaced .vhnav so nothing can
   collide with lt-styles. Icons are lucide — the app renders them with its
   own createIcons() boot alongside its native header icons. */
const NAV_STYLE = `
<style id="vhnav-style">
  .vhnav { display: flex; align-items: center; gap: 2px; flex: none; margin: 0 10px; padding: 3px;
    background: rgba(255, 255, 255, 0.03); border: 1px solid rgba(139, 133, 163, 0.22); border-radius: 999px; }
  .vhnav a { display: inline-flex; align-items: center; gap: 6px; flex: none; padding: 4px 11px; border-radius: 999px;
    color: #8b85a3; font-size: 11px; font-weight: 500; text-decoration: none; white-space: nowrap;
    transition: color 120ms cubic-bezier(0.23, 1, 0.32, 1), background 120ms cubic-bezier(0.23, 1, 0.32, 1); }
  .vhnav a i, .vhnav a svg { width: 12px; height: 12px; stroke-width: 1.7; opacity: 0.75; }
  .vhnav a img { width: 14px; height: 14px; display: block; }
  .vhnav a:hover { color: var(--text, #f6f5fb); background: rgba(255, 255, 255, 0.05); }
  .vhnav a:active { transform: scale(0.97); }
  .vhnav a.on { color: var(--text, #f6f5fb); background: rgba(255, 255, 255, 0.09); font-weight: 600; }
  .vhnav a.on i, .vhnav a.on svg { color: var(--teal, #00d4d4); opacity: 1; }
  @media (max-width: 1460px) { .vhnav a span { display: none; } .vhnav a { padding: 5px 9px; } .vhnav a i, .vhnav a svg { width: 13px; height: 13px; } }
  @media (max-width: 900px) { .vhnav a { display: none; } .vhnav a.vhnav-home { display: inline-flex; } .vhnav { margin: 0 2px; padding: 2px; } }
  /* the app has a light theme — the nav must survive both */
  .theme-light .vhnav { background: rgba(10, 12, 22, 0.04); border-color: rgba(10, 12, 22, 0.16); }
  .theme-light .vhnav a { color: rgba(24, 26, 36, 0.55); }
  .theme-light .vhnav a:hover { color: #14161e; background: rgba(10, 12, 22, 0.06); }
  .theme-light .vhnav a.on { color: #14161e; background: rgba(10, 12, 22, 0.09); }
</style>
`;

/* the hub's places, continued inside the app's own header. The flamingo pill
   is the constant — on phones it alone remains, the way home. */
const NAV = `
      <!-- Vice Hub nav (generated by tools/gen-academy.js — edit THERE) -->
      <nav class="vhnav" aria-label="Vice Hub">
        <a class="vhnav-home" href="${HUB}" title="The Vice Hub"><img src="/vice/vice-terminal-64.png" alt="Vice Hub" /></a>
        <a href="${HUB}#/" title="Your customizable dashboard"><i data-lucide="layout-dashboard"></i><span>Dashboard</span></a>
        <a href="${HUB}#/chart" title="Full-page charting"><i data-lucide="candlestick-chart"></i><span>Chart</span></a>
        <a href="${HUB}#/scanner" title="Vice Scanner — track the top Hyperliquid wallets"><i data-lucide="radar"></i><span>Scanner</span></a>
        <a href="${HUB}#/gallery" title="Every element, live-previewable"><i data-lucide="shapes"></i><span>Gallery</span></a>
        <a class="on" href="/academy" aria-current="page" title="You are here"><i data-lucide="book-open"></i><span>Academy</span></a>
      </nav>
`;

let html = fs.readFileSync(SRC, 'utf8');
const must = (needle, what) => {
  if (!html.includes(needle)) {
    console.error(`gen-academy: anchor missing — ${what} (${needle.slice(0, 60)}…)`);
    process.exit(1);
  }
};

// app-root-relative "./x" means "this app" — here, the academy door itself
// (served at /academy WITHOUT a trailing slash: trailingSlash:false, so a
// raw "./" would resolve to the ROOT site and silently drop the hub chrome)
html = html.replace(/(src|href)="\.\/([^"]*)"/g,
  (m, a, p) => `${a}="/academy${p ? `/${p}` : ''}"`);
// root-relative assets → absolute; dot-prefixed refs never get blindly
// root-anchored (a future ../x must be handled deliberately, not mangled)
html = html.replace(/(src|href)="(?!https?:|\/\/|\/|#|data:|mailto:|\.)([^"]+)"/g, '$1="/$2"');

// identity: the hub's Academy; never competes with the root site in search
must('<title>', 'title tag');
html = html.replace(/<title>[^<]*<\/title>/, '<title>Vice Academy — Liquidity Theory</title>');
html = html.replace(/<link rel="canonical"[^>]*\/>/, '<link rel="canonical" href="https://liqtheory.com/" />');
if (!/name="robots"/.test(html)) {
  must('<meta charset="UTF-8" />', 'charset meta');
  html = html.replace('<meta charset="UTF-8" />', '<meta charset="UTF-8" />\n  <meta name="robots" content="noindex, nofollow" />');
}

// styles ride at the end of <head>
must('</head>', 'head close');
html = html.replace('</head>', `${NAV_STYLE}</head>`);

// the nav joins the app's own header row, between the title block and the
// BTC ticker; if the ticker ever moves, fall back to the header open so a
// cosmetic app edit can't block the whole deploy — only a vanished
// .top-header does (that IS drift worth stopping for)
const TICKER_ANCHOR = '<div class="btc-ticker" id="btc-ticker"';
const HEADER_ANCHOR = '<header class="top-header">';
if (html.includes(TICKER_ANCHOR)) {
  html = html.replace(TICKER_ANCHOR, `${NAV}\n      ${TICKER_ANCHOR}`);
} else {
  console.warn('gen-academy: btc-ticker anchor moved — nav falls back to the header open');
  must(HEADER_ANCHOR, 'app top-header');
  html = html.replace(HEADER_ANCHOR, `${HEADER_ANCHOR}\n${NAV}`);
}

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT, html);
console.log(`academy/index.html generated (${html.length} bytes, in-header nav)`);
